# Default values for oidc_passthrough.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

oidcDepl:
  #image: jviqlik/passthruoidc:v1.0
  image: qristof/qseokssooidc
  imagePullPolicy: Always
  #imagePullPolicy: IfNotPresent
  client_id: "singlesignon"
  client_secret: "thanksjviandcsw"
          # /!\ id and secret of the only client in the passthrough-oidc provider
          # --> this is also put into identity-providers section of qliksense.yaml    
  path_prefix: "/singlesignon" 
          # /!\ The ingress-route of the oidc provider's base address, one level below qliksense,
          # start with / slash, for example "/oidc" which means, this oidc-passthrough service
          # will have the home address https://elastic.example/oidc (where elastic.example is 
          # your sense server.  
  oidc_redirects: "https://elastic.example/login/callback"
          # The oidc
          # be "https://elastic.example/login/callback" as this is the expected return-to
          # /!\ mandatory to tell the oidc the allowed qlik-sense return addresses, this should
          # separate multiple values with comma  
  post_logout_redirects: "http://localhost:5656/tryme.html"
          # /!\ Allowed redirect urls after logout, comma-separated. The effective redirect
          # after logout is not configured here, but in qliksense.yaml (postLogoutRedirectUri) 
          # The entry here is just for the oidc to accept the possible post-logout uri values   
   
  # jwt passphrase (if HS256 is used) or the public key (if RS256 is used, recommended)  
  #jwt_decrypt_publickey: "shhhh"
  jwt_decrypt_publickey: |-
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzyis1ZjfNB0bBgKFMSv
    vkTtwlvBsaJq7S5wA+kzeVOVpVWwkWdVha4s38XM/pa/yr47av7+z3VTmvDRyAHc
    aT92whREFpLv9cj5lTeJSibyr/Mrm/YtjCZVWgaOYIhwrXwKLqPr/11inWsAkfIy
    tvHWTxZYEcXLgAXFuUuaS3uF9gEiNQwzGTU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0
    e+lf4s4OxQawWD79J9/5d3Ry0vbV3Am1FtGJiJvOwRsIfVChDpYStTcHTCMqtvWb
    V6L11BWkpzGXSW4Hv43qa+GSYOD2QU68Mb59oSk2OB+BtOLpJofmbGEGgvmwyCI9
    MwIDAQAB
    -----END PUBLIC KEY-----    
    
  signin_endpoint_enabled: "true"
          # Setting if you want the /signin endpoint (true) or not
  forward_urls: "^https://elastic.example"
          # /!\ security setting so that the /signin endpoint cannot be used to forward browsers
          # to anywhere else than desired. This is a regex value to validate allowed forward urls 
          # example "^https://elastic.example" (=any url that starts with https://elastic.example)    
  msg_login: "Logging in..."  # title shown shortly when token was ok on /signin endpoint
  msg_token_accepted: "Token accepted." # text shown shortly when token was ok on /signin endpoint
  error_title: "Ooops! something went wrong"
  error_redir_url: "http://localhost:5656/tryme.html"
  error_redir_after_seconds: 3
  #error_msg_no_claim: ""
  #error_msg_bad_token: ""
  #error_msg_no_params: ""
  #error_msg_no_jwt: ""
  #error_msg_no_fwd: ""
  #error_msg_bad_fwd: ""
  
  
