# Default values for oidc_passthrough.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

oidcDepl:
  image: jviqlik/passthruoidc:0.92
  imagePullPolicy: Always
  jwt_decrypt_publicKey: Qlik1234
  client_id: foo
  client_secret: bar
  redirect_uris: https://qseok.qlik-poc.com/login/callback
oidcService:
  portInNode: 3000
  exposedOnPort: 3000
