# Default values for oidc_passthrough.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

oidcDepl:
  image: jviqlik/passthruoidc:0.92
  imagePullPolicy: Always
  path_prefix: "/oidc"
  client_id: "foo"
  client_secret: "thanksjviandcsw"
  oidc_redirects: "https://elastic.example/login/callback"
  forward_urls: "^https://elastic.example"
  post_logout_redirects: "https://www.qlik.com"
  #jwt_decrypt_publickey: "shhhh"
  jwt_decrypt_publickey: |-
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzyis1ZjfNB0bBgKFMSv
    vkTtwlvBsaJq7S5wA+kzeVOVpVWwkWdVha4s38XM/pa/yr47av7+z3VTmvDRyAHc
    aT92whREFpLv9cj5lTeJSibyr/Mrm/YtjCZVWgaOYIhwrXwKLqPr/11inWsAkfIy
    tvHWTxZYEcXLgAXFuUuaS3uF9gEiNQwzGTU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0
    e+lf4s4OxQawWD79J9/5d3Ry0vbV3Am1FtGJiJvOwRsIfVChDpYStTcHTCMqtvWb
    V6L11BWkpzGXSW4Hv43qa+GSYOD2QU68Mb59oSk2OB+BtOLpJofmbGEGgvmwyCI9
    MwIDAQAB
    -----END PUBLIC KEY-----    
  msg_login: "Logging in..."
  msg_token_accepted: "Token accepted."
  msg_no_cookie: "Please go to your main web app and restart login process"
  fwd_no_cookie: "https://www.qlik.com"
  
