# Default values for oidc_passthrough.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

oidcDepl:
  image: jviqlik/passthruoidc:0.92
  imagePullPolicy: Always
  path_prefix: "/oidc"
  client_id: "foo"
  client_secret: "thanksjviandcsw"
  oidc_redirects: "https://elastic.example/login/callback"
  post_logout_redirects: "https://www.qlik.com"
  jwt_decrypt_publickey: "shhhh"
  msg_login: "Logging in..."
  msg_token_accepted: "Token accepted."
  msg_no_cookie: "Please go to your main web app and restart login process"
  fwd_no_cookie: "https://www.qlik.com"
  
  
