apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidcpassthrough
  labels:
    app: oidcpassthrough
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: oidcpassthrough
  template:
    metadata:
      labels:
        app: oidcpassthrough
    spec:
      containers:
      - name: oidcpassthrough
        image: {{ .Values.oidcDepl.image}}
        env:

        - name: PATH_PREFIX
          value: "{{.Values.oidcDepl.path_prefix}}"

        - name: CLIENT_ID
          value: "{{.Values.oidcDepl.client_id}}"
          
        - name: CLIENT_SECRET  
          value: "{{.Values.oidcDepl.client_secret}}"

        - name: JWT_DECRYPT_PUBLICKEY
          value: {{ toYaml .Values.oidcDepl.jwt_decrypt_publickey }}
          
        - name: OIDC_REDIRECTS
          value: "{{.Values.oidcDepl.oidc_redirects}}"
          
        - name: POST_LOGOUT_REDIRECTS
          value: "{{.Values.oidcDepl.post_logout_redirects}}"

        - name: SIGNIN_ENDPOINT_ENABLED
          value: "{{.Values.oidcDepl.signin_endpoint_enabled}}"

{{- if .Values.oidcDepl.forward_urls }}     
        - name: FORWARD_URLS
          value: "{{.Values.oidcDepl.forward_urls}}"  
{{- end }}
{{- if .Values.oidcDepl.msg_login }}          
        - name: MSG_LOGIN
          value: "{{ .Values.oidcDepl.msg_login }}"
{{- end }}
{{- if .Values.oidcDepl.msg_token_accepted }}          
        - name: MSG_TOKEN_ACCEPTED
          value: "{{ .Values.oidcDepl.msg_token_accepted }}"
{{- end }}
{{- if .Values.oidcDepl.error_title }}          
        - name: ERROR_TITLE
          value: "{{ .Values.oidcDepl.error_title }}"
{{- end }}
{{- if .Values.oidcDepl.error_msg_no_claim }}          
        - name: ERROR_MSG_NO_CLAIM
          value: "{{ .Values.oidcDepl.error_msg_no_claim }}"
{{- end }}
{{- if .Values.oidcDepl.error_msg_bad_token }}          
        - name: ERROR_MSG_BAD_TOKEN
          value: "{{ .Values.oidcDepl.error_msg_bad_token }}"
{{- end }}
{{- if .Values.oidcDepl.error_msg_no_params }}          
        - name: ERROR_MSG_NO_PARAMS
          value: "{{ .Values.oidcDepl.error_msg_no_params }}"
{{- end }}
{{- if .Values.oidcDepl.error_msg_no_jwt }}          
        - name: ERROR_MSG_NO_JWT
          value: "{{ .Values.oidcDepl.error_msg_no_jwt }}"
{{- end }}
{{- if .Values.oidcDepl.error_msg_no_fwd }}          
        - name: ERROR_MSG_NO_FWD
          value: "{{ .Values.oidcDepl.error_msg_no_fwd }}"
{{- end }}
{{- if .Values.oidcDepl.error_msg_bad_fwd }}          
        - name: ERROR_MSG_BAD_FWD
          value: "{{ .Values.oidcDepl.error_msg_bad_fwd }}"
{{- end }}
{{- if .Values.oidcDepl.error_redir_url }}          
        - name: ERROR_REDIR_URL
          value: "{{ .Values.oidcDepl.error_redir_url }}"
{{- end }}
{{- if .Values.oidcDepl.error_redir_after_seconds }}          
        - name: ERROR_REDIR_AFTER_SECONDS
          value: "{{ .Values.oidcDepl.error_redir_after_seconds }}"
{{- end }}

        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"

        imagePullPolicy: {{ .Values.oidcDepl.imagePullPolicy}}
        ports:
        - containerPort: 3000
        
