apiVersion: v1
kind: Service
metadata:
  name: oidcpassthrough-service
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: oidcpassthrough-service
  selector:
    app: oidcpassthrough